# Text Repesentation

In [1]:
# 1. Bag of words
# we use countvectorization

In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.DataFrame({'text':['people watch cricket','people was player', 'people write comment',
                         'cricket play comment'],'output':[1,1,0,0]})

In [5]:
df

text  output
0  people watch cricket       1
1     people was player       1
2  people write comment       0
3  cricket play comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv=CountVectorizer()

In [8]:
bow=cv.fit_transform(df['text'])

In [9]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'was': 5, 'player': 4, 'write': 7, 'comment': 0, 'play': 3}


In [10]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 1 0 1 1 0 0]]


In [11]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [12]:
# 2-N-grams

In [13]:
# cv=CountVectorizer(ngram_range(2,2))

In [14]:
v=CountVectorizer(ngram_range=(1,2))

In [19]:
bow=v.fit_transform(df['text'])

In [20]:
df['text']

0    people watch cricket
1       people was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [21]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 5, 'watch cricket': 13, 'was': 10, 'player': 9, 'people was': 4, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 6, 'write comment': 15, 'play': 7, 'cricket play': 2, 'play comment': 8}


In [22]:
# TF(Term Frequency)
# 2. IDF(Inverse Document Frequency)

In [24]:
# TF(t,d) (Number of occurences of term t in document d)/(Total number of terms in the document d)

# example 
#d1 people watch cricket.

#tf(people, d1) = 1/3

#d2 match was match.
#tf(match, d2) = 2/3


In [25]:
#IDF(t) = Loge (Total number of documents in the corpus)/(Number of documents with term t in them)
# here corpus means number of sentences

# Example ==>
#d1 people watch cricket.
#d2 = cricket was cricket.
#d3 people write comment.
#d4 cricket write comment

#idf(cricket) = Log(4/4)
#idf (people) = Log(4/2)

In [26]:
# we can use this by apply feature_extraction method in sklearn

In [27]:
df

text  output
0  people watch cricket       1
1     people was player       1
2  people write comment       0
3  cricket play comment       0

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.55349232, 0.44809973, 0.        , 0.        ,
        0.        , 0.70203482, 0.        ],
       [0.        , 0.        , 0.41137791, 0.        , 0.64450299,
        0.64450299, 0.        , 0.        ],
       [0.55349232, 0.        , 0.44809973, 0.        , 0.        ,
        0.        , 0.        , 0.70203482],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [30]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.22314355 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


# WordEmbedding

In [ ]:
In natural language preprocessing word embedding is a term used for the 