# 4. diag ==> this function createsa two dimensional array with all the diagonal element as the given value and rest are zero

In [1]:
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5. randint ==> this func is use to generate a random number b/w a given range

syntax : randint(min_value,max_value,total_no)

In [1]:
import numpy as np
a=np.random.randint(1,10,3)
a

array([1, 5, 4])

# 6. rand()==> func use to generate a random no b/w 0 to 1
syntax==rand(no of value)

In [4]:
import numpy as np
a=np.random.rand(3)
a

array([0.94542951, 0.66175375, 0.224512  ])

# 7.randn()==> func use to generate a random no from -3 to close 3 it may return posittive or negatiev 

# reshapinng data

In [5]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([44, 47, 25, 39,  2,  4, 37, 11, 28, 25, 45, 28])

In [6]:
# n(r)*n(c)=n(total_element)

In [7]:
a.shape

(12,)

In [8]:
a=a.reshape(2,6)
a

array([[44, 47, 25, 39,  2,  4],
       [37, 11, 28, 25, 45, 28]])

In [9]:
a=a.reshape(3,4)
a

array([[44, 47, 25, 39],
       [ 2,  4, 37, 11],
       [28, 25, 45, 28]])

In [10]:
a=a.reshape(6,2)
a

array([[44, 47],
       [25, 39],
       [ 2,  4],
       [37, 11],
       [28, 25],
       [45, 28]])

In [11]:
a=a.reshape(12,1)
a

array([[44],
       [47],
       [25],
       [39],
       [ 2],
       [ 4],
       [37],
       [11],
       [28],
       [25],
       [45],
       [28]])

In [12]:
import numpy as np
a=np.random.randint(1,100,64)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [15]:
a.reshape(1,64)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [16]:
a.reshape(2,32)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [17]:
a.reshape(64,1)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [18]:
a.reshape(32,2)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [20]:
a.reshape(4,16)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [21]:
a.reshape(8,8)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

In [23]:
a.reshape(16,4)
a

array([15, 88, 41, 58, 99, 11, 28, 78, 66, 39, 56, 86, 62, 93,  9, 28, 41,
       38, 94, 68, 21, 60, 40, 32, 10,  8, 93, 42, 55,  1, 42, 52, 25, 64,
       92,  3, 99, 84, 38, 10, 76, 76, 12,  2, 90, 99, 82, 80, 61, 18, 35,
       86, 58, 45, 40, 74, 35, 97, 88, 16, 53, 20, 78, 33])

# principal  of -1

In [24]:
a=a.reshape(-1,4)
a

array([[15, 88, 41, 58],
       [99, 11, 28, 78],
       [66, 39, 56, 86],
       [62, 93,  9, 28],
       [41, 38, 94, 68],
       [21, 60, 40, 32],
       [10,  8, 93, 42],
       [55,  1, 42, 52],
       [25, 64, 92,  3],
       [99, 84, 38, 10],
       [76, 76, 12,  2],
       [90, 99, 82, 80],
       [61, 18, 35, 86],
       [58, 45, 40, 74],
       [35, 97, 88, 16],
       [53, 20, 78, 33]])

# seed func() ==> we know that randint func generates random no. everytime we run the program ,new set of random no is generated
,so solve this problem we use seed func  

In [33]:
import numpy as np
np.random.seed(7)
a=np.random.randint(1,100,10)
a

array([48, 69, 26, 68, 84, 24, 93, 58, 15, 24])

# view vs copy ==> when we slice a sub array from an array,it may be done by two ways

In [34]:
# view
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=a[3:6]
b[:]=0
a

array([1, 2, 3, 0, 0, 0, 7, 8])

In [36]:
# copy
a=np.array([1,2,3,4,5,6,7,8])
b=a[3:6].copy()
b[:]=0
a

array([1, 2, 3, 4, 5, 6, 7, 8])

# conditional statement

In [38]:
import numpy as np
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [40]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [41]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [42]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

# operation on array

In [44]:
import numpy as np
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [45]:
a+2

array([3, 4, 5, 6])

In [46]:
a**2

array([ 1,  4,  9, 16])

In [48]:
a=np.array([1,2,3,4]).reshape([2,2])
a

array([[1, 2],
       [3, 4]])

In [52]:
b=np.array([5,6,7,8]).reshape([2,2])
b

array([[5, 6],
       [7, 8]])

In [53]:
a+b

array([[10, 12],
       [14, 16]])

In [54]:
a-b

array([[0, 0],
       [0, 0]])

In [55]:
a/b

array([[1., 1.],
       [1., 1.]])

In [56]:
a*b #simple mult.

array([[25, 36],
       [49, 64]])

In [57]:
a.dot(b) #matrix multiplication

array([[ 67,  78],
       [ 91, 106]])

In [58]:
import numpy as np
a=np.array([10,20,30,40,50])
np.min(a)

10

In [59]:
np.max(a)

50

In [61]:
np.argmin(a)#return indexing of min value

0

In [62]:
np.argmax(a)#return indexing of max value

4

In [65]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [64]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# linspace()==> return value b/w given range and with same gap b/w consicutive elements

In [2]:
import numpy as np
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.umique(arr,return_index=true,return_count=true)
return 3 array 1. arr with unique value,2. arr with respective index value,3. arr with couning of frequency

In [68]:
a=np.array([10,20,30,40,20,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 5], dtype=int64),
 array([1, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical syacking

In [69]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [70]:
b

array([5, 6, 7, 8])

In [71]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])