In [1]:
# introduction to numpy:

# why numpy is better than list?
# 1. same data type ==> array
# 2. memory consume ==> numpy less, array high
# 3. computation power ==> numpy high,list less
# 4. function ==> numpy high , list less

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5]
type(a)

list

In [4]:
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [5]:
type(b)

numpy.ndarray

In [6]:
a=[]
size=int(input("enter the number of index for a : "))
for i in range(size):
    val=int(input("enter the elements of list :"))
    a.append(val)
    
b=np.array(a)
b

enter the number of index for a : 4
enter the elements of list :1
enter the elements of list :2
enter the elements of list :3
enter the elements of list :4


array([1, 2, 3, 4])

# how to checkshape and size of an array ?

In [7]:
# esc+1 
# shift + enter

In [8]:
# shape =n(rows) , n(columns)
# size=total_elements ==> n(rows)*n(columns)

In [10]:
print("total shape ",b.shape)
print("total size ",b.size)

total shape  (4,)
total size  4


In [12]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print("total shape ",b.shape)
print("total size ",b.size)

total shape  (3, 3)
total size  9


In [14]:
# image ==> pixels ==> (0,255)px ==> 0px(complete black) ,255px(complete white)

# convert ==> grayscale image ==>
# image(pixels) ==> normalization(0,1)==>0px black,1px white

# 0,1 ==? neoron system

# matrix ==> rows,columns ==>
# symmatric matrix ==> n(rows)==n(columns)
# asymmatric matrix ==> n(rows)!=n(columns)
# diagonal elements =[(1,1),(2,2),(3,3)....(n,n)]

# 1. zeros() ==> it will create an array in which all elements are zero

In [15]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [16]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 2. once() ==> it will create an array in which all elements are one

In [18]:
a=np.ones(3)
a

array([1., 1., 1.])

In [19]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# 3. eye() ==> it will create an array in which diagonal elements are one 

In [20]:
a=np.eye(3,4)##asymmatric matix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
a=np.eye(4)##symmatric matix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])