In [1]:
# write statement to import numpy
import numpy as np

In [3]:
# create an array using numpy
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# create an array of 10 random integer
a=np.random.randint(1,100,10)
a

array([73,  1, 21, 55, 67, 29, 96, 24, 86, 46])

In [6]:
# create an array of element from 10-20
a=np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
# create an array which contain value 5,10 times
a=np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
# create a 1d array and convert it into 3*3 matrix
a=np.array([1,2,3,4,5,6,7,8,9])
a=a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# create a 2d array of  size 3*3 but all element should be b/w 0 and 1
a=np.random.rand(3,3)
a

array([[0.04611284, 0.30826477, 0.76229714],
       [0.84926149, 0.4798017 , 0.32555555],
       [0.02960602, 0.87355342, 0.34819229]])

In [18]:
# concatenate 2d array horizontally and vertically 
a=np.array([10,20,30,40])
b=np.array([20,3,40,50])
np.hstack((a,b))

array([10, 20, 30, 40, 20,  3, 40, 50])

In [19]:
np.vstack((a,b))

array([[10, 20, 30, 40],
       [20,  3, 40, 50]])